const topicos={
manusear:{resumo:'Reduza o contato e dê apoio à fotografia durante o manuseio.',faca:['Lave e seque bem as mãos; use luvas nitrílicas limpas para negativos, vidro e metal.','Segure pelas bordas ou pelo invólucro.','Trabalhe sobre uma superfície limpa, seca e sem alimentos.'],evite:['Tocar a área da imagem.','Dobrar, empilhar sem apoio ou usar clipes e elásticos.','Escrever sobre a frente ou pressionar o verso.']},
guardar:{resumo:'Um invólucro adequado e um ambiente estável diminuem a deterioração.',faca:['Use envelopes, pastas ou caixas destinados à conservação fotográfica.','Guarde em área limpa, estável e longe do chão.','Identifique o invólucro, não a fotografia.'],evite:['Porões, sótãos, garagens e locais próximos a água ou aquecedores.','Fita adesiva, cola comum e álbuns autoadesivos.','Misturar fotografias úmidas ou com mofo às demais.']},
exibir:{resumo:'Toda luz provoca algum dano cumulativo; exibir uma cópia protege o original.',faca:['Prefira uma cópia para exposição prolongada.','Use montagem de conservação e proteção UV apropriada.','Mantenha longe de sol direto, calor e umidade.'],evite:['Colar a foto no fundo.','Exposição permanente de original único ou valioso.','Encostar a imagem diretamente no vidro.']},
digitalizar:{resumo:'A cópia digital amplia o acesso, mas não substitui o cuidado com o original.',faca:['Limpe o equipamento e apoie a foto sem forçar.','Salve uma cópia de alta qualidade e arquivos de acesso separados.','Mantenha cópias digitais em mais de um local e registre nomes e datas.'],evite:['Forçar álbuns frágeis contra o vidro do scanner.','Descartar o original após digitalizar.','Depender de um único pendrive ou aparelho.']},
danificada:{resumo:'Interrompa a causa do dano e peça ajuda antes de uma intervenção irreversível.',faca:['Isole com segurança itens com suspeita de mofo.','Documente a condição sem manipular repetidamente.','Procure um conservador-restaurador para peças importantes.'],evite:['Aplicar água, álcool, produto de limpeza ou calor.','Separar à força foto aderida a vidro ou álbum.','Usar fita adesiva para reparar rasgos.']}
};
function obterTopico(id){return topicos[id]||topicos.manusear}
function itens(lista){return lista.map(x=>`<li>${x}</li>`).join('')}
if(typeof document!=='undefined'){const mostrar=id=>{const t=obterTopico(id);document.querySelector('#resumo').textContent=t.resumo;document.querySelector('#faca').innerHTML=itens(t.faca);document.querySelector('#evite').innerHTML=itens(t.evite);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('ativo',b.dataset.topico===id))};document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>mostrar(b.dataset.topico)));mostrar('manusear')}
if(typeof module!=='undefined')module.exports={topicos,obterTopico};
